### ISSUE TITLE
Timezone offset

### ISSUE THREAD

**Issue by stephenfmann** [stephenfmann/kindle-clippings#4]
Include timezone offset: source files "My Clippings.txt" does not include a timezone. We could default to the user's system time zone. This is configurable by changing the TZ environment variable.

Suggested as a consequence of pull request #3.

**Comment by monking** [comment]
For behavior, I favor a `-z` flag (no value passed) which causes the script to use the `TZ` environment variable in the date output.

As far as implementation, I'm less certain.
I'd tried including `%z` in the `strftime()` format string, but it didn't result in the UTC offset being included in the output.

per [strftime.org](https://strftime.org/):
> UTC offset in the form +HHMM or -HHMM (empty string if the the object is naive).

It seems the date object needs to have the timezone offset defined explicitly when its value is set (I'm guessing what "naïve" means in this context).

**Comment by stephenfmann** [comment]
Added with commit 837d869512d37342a4dfb3cfb3ac53126670672f.

If the -z flag is used, the system timezone will be included with all timestamps. If not, the timestamps will remain naive.

Instead of the environment variables I used:

`from dateutil.tz import tzlocal`
